### ISSUE TITLE
CORS not working since 1.0.3

### ISSUE THREAD

**Issue by ant-magic42** [co-cart/cocart-cors#20]
I noticed the CoCart CORS plugin isn't working since 1.0.3.

The CORS headers are no longer present it's as if this extension isn't installed.

The behavior I observe is that the CORS extension isn't activated - the `cocart_init` action doesn't call `\CoCart\Cors\Plugin::init();`.

CoCart version 3.9.0
PHP 8.1

**Comment by seb86** [comment]
If you changed `cocart_init` to `plugins_loaded` instead, can you tell me if that works for you?

I suspect it's a load issue and didn't consider it when releasing. The main CoCart plugin name has changed in v4 so WordPress is loading the plugin before hand.

**Comment by ant-magic42** [comment]
@seb86 I will try your suggestion and report back 👍

**Comment by ant-magic42** [comment]
@seb86  I can confirm that if I change this line https://github.com/co-cart/cocart-cors/blob/fa5cfcb/cocart-cors.php#L41 to use `plugins-loaded` instead of `cocart_init` then it works fine.

**Comment by ant-magic42** [comment]
@seb86 I don't understand this issue enough to know but would it help if I made a PR to do this?  Or are there wider implications?  Or you have another plan?

**Comment by seb86** [comment]
> @seb86 I don't understand this issue enough to know but would it help if I made a PR to do this? Or are there wider implications? Or you have another plan?

Sorry for the delay. Life stuff happened. Will have this issue resolved this week.

**Comment by seb86** [comment]
Released
